version: "3.8"
services:
  odd-collector-aws:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: odd-collector
    restart: always
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PLATFORM_HOST_URL=${PLATFORM_HOST_URL}
