default_pulling_interval: 10 # in minutes, if not specified collector will be run once
token: "**********" # OpenDataDiscovery collector token
platform_host_url: "http://localhost:8080"
plugins:
  - type: bigquery_storage
    name: bigquery_storage
    project: opendatadiscovery
