name: Build and publish PyPI artifact

on:
  workflow_dispatch:

jobs:
  build_and_publish_package:
    name: Build and publish the PyPi package
    runs-on: ubuntu-latest
    concurrency: publishing
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'odd-collector-sdk'

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.2'

      - name: Install dependencies
        working-directory: odd-collector-sdk
        run: poetry install

      - name: Run tests
        working-directory: odd-collector-sdk
        run: poetry run pytest .

      - name: Patch package version
        working-directory: odd-collector-sdk
        run: |
          poetry version patch
          echo "VERSION = \"$(poetry version -s)\"" > odd_collector_sdk/__version__.py

      - name: Run Dockerfile to build and publish package into PyPI
        working-directory: odd-collector-sdk
        run: |
          docker build -f Dockerfile . -t ignored \
            --build-arg PYPI_USERNAME=${{ secrets.PYPI_USERNAME }} \
            --build-arg PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}

      - name: Update repository with up-to-date and version
        run: |
          git config --global user.email "opendatadiscovery-bot@provectus.com"
          git config --global user.name "OpenDataDiscovery Bot"
          if [ -n "$(git status --porcelain)" ]
          then
            git add .
            git commit -m "sdk(chore): Bump package version"
            git push origin main
          fi
